export default {
  name:"seller",
  api:{
    getIndexData:{
      url:"/indexData",
      method:"get",
      corsUrl:'/3004'
    },
    getCateNavData:{
      url:"/getCateNavData",
      method:"get",
      corsUrl:'/3004'
    },
    getCateList:{
      url:"/getCateList",
      method:"get",
      corsUrl:'/3004'
    }
}
}
